services:
- name: veriguard-backend
  env: docker
  dockerfilePath: ./Dockerfile
  buildCommand: "docker build -t veriguard-backend ."
  envVars:
    - key: GEMINI_API_KEY
      value: your_gemini_api_key
    - key: OPENAI_API_KEY  # Updated from DEEPSEEK_API_KEY to match OpenRouter/OpenAI client expectation
      value: your_deepseek_api_key
    - key: GOOGLE_API_KEY
      value: your_google_api_key
  regions:
    - singapore
  healthCheckPath: "/"